### PR TITLE
Remove calf patches

### LINKED ISSUE #28: build failed with Hunk #1 FAILED at 54
Hi,

I get this when I run the build command:

`==> Installing calf from david0/audio
==> Patching
==> Applying d2f174083d97ce0f6930fc28764fdec80810f464.patch
patching file configure.ac
Hunk #1 succeeded at 159 with fuzz 2 (offset 21 lines).
patching file src/Makefile.am
Hunk #1 FAILED at 54.
1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.am.rej

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/david0/homebrew-audio/issues
`
Anything I can do about that?
Regards,
Robert

### PR DESCRIPTION
**Pull request by tresf**
Closes #28
Per https://github.com/calf-studio-gear/calf/pull/46

Learned/cherry-picked from:
* https://github.com/calf-studio-gear/calf/issues/72#issuecomment-222347373

Testing steps:

```bash
brew untap david0/homebrew-audio
brew tap tresf/homebrew-audio
brew install --HEAD calf
ln -s $(brew --prefix calf)/lib/lv2/calf.lv2  ~/Library/Audio/Plug-Ins/LV2/calf.lv2
```

What works:
* Plug-Ins load and make sound

What doesn't work:
* Suil UI stuff seems to be broken, so no UI.  Might be a configuration issue on my local, but x42 plugins using Qt5 Cocoa work, so I'm not entirely sure (Testing with LMMS LV2 snapshot from here https://github.com/LMMS/lmms/pull/7201).

### CODE REVIEW

File: Formula/calf.rb [hunk 1]
```diff
@@ -17,21 +17,6 @@ class Calf < Formula
...
 
-
-  head do
-    # Test if linker supports nodelete
-    patch do
-      url "https://github.com/david0/calf/commit/e56702017a3904970f42357a931db949945f43ce.patch"
-      sha256 "89c0765cafe81600774116efd8fa48a6d4878d6913e7f9c05870da7d9f6a3d77"
-    end
-  end
-  stable do
```
Comment (david0) [inline Formula/calf.rb:28]: if we remove stable here, doesn't that require an updated `:tag=>` version too to work?

Comment (tresf) [reply Formula/calf.rb:28]: Good catch.  To be honest, I have no idea how this command even works (cherry-picked):

https://github.com/calf-studio-gear/calf/issues/72#issuecomment-222347373

I'll do some more testing and report my findings.

Comment (tresf) [reply Formula/calf.rb:28]: So I understand the `--HEAD` and default `stable` options better now. 

Although I agree, your stable patch should still be needed -- since your upstream [PR was merged](https://github.com/calf-studio-gear/calf/pull/46) well AFTER the [latest stable](https://github.com/calf-studio-gear/calf/releases/tag/0.90.3) was released -- it's not needed on my machine.  Any idea why?

Steps:

```bash
brew remove calf
brew install calf # no --HEAD option, shows `0.90.3`
# success
```

Comment (tresf) [reply Formula/calf.rb:28]: I've reverted the `stable` patch to it's current form for now.

>  doesn't that require an updated `:tag=>` version too to work?

I tried to find version-specific documentation/examples at Homebrew and Formulas but couldn't find one.   I would be happy to add an explicit version check to this with a small amount of direction as to how this should be performed. 🍻

Comment (david0) [reply Formula/calf.rb:28]: Ok, that should work. We have to keep the stable patches until the  calf releases a new version (creates a new tag). I'm not sure why they are not doing that since years?
Anyway, we can merge it as-it-is any update the stable version later.

About that the change does not make a difference when running brew install: I'm not completely sure, but I guess the "bottle" is still there and rebuild is skipped because of that.
try running with `-s`
```
-s, --build-from-source          Compile formula from source even if a
                                   bottle is provided. Dependencies will still
                                   be installed from bottles if they are
                                   available
```

**Comment by david0** [comment]
thanks!
